### ISSUE TITLE
Hover effect on image 

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/Marketing-website#1]
![other-prod](https://user-images.githubusercontent.com/54848535/130161626-a61ab0ff-7c57-478e-a06d-2b58d1deeeb9.JPG)

add hover effect on each of the products on the right . the hover effect should display a ( lorem ipsum ) text at the center of the product when hovered

**Comment by rituraj8503** [comment]
Hey @Godwindaniel10 , may I please take this issue?

**Comment by godwin-morwin** [comment]
@rituraj8503 sure

**Comment by SUDESHNA1234** [comment]
Can I work on it?

**Comment by godwin-morwin** [comment]
> Can I work on it?

i think @rituraj8503 is working on this issue currently. thanks for at least showing interest in this issue.
